export const TOGGLE_FLAG = 'react-minesweeper/TOGGLE_FLAG'
export const INIT = 'react-minesweeper/INIT'
export const CHANGE_DIFFICULTY = 'react-minesweeper/CHANGE_DIFFICULTY'
export const GAMEOVER = 'react-minesweeper/GAMEOVER'
export const CLEAR = 'react-minesweeper/CLEAR'
